### PR TITLE
trade places with other contributors

### PR DESCRIPTION
**Pull request by will-s-205**

### CODE REVIEW

**Review by michaella23 — APPROVED** [review]
Approving this time, even though an issue was not created prior. Please review changes to General Guidelines in [CONTRIBUTING.md](https://github.com/michaella23/bootcamp-collab/blob/main/CONTRIBUTING.md).

**Comment by michaella23** [comment]
I'd also be interested to know why you wanted to make this particular change @will-s-205 . 🙂

**Comment by will-s-205** [comment]
> I'd also be interested to know why you wanted to make this particular change @will-s-205 . 🙂

Seem like website with a real photo and references to portfolio have more chances to get attention from recruiters. This is just my opinion.

**Comment by michaella23** [comment]
> > I'd also be interested to know why you wanted to make this particular change @will-s-205 . 🙂
> 
> Seem like website with a real photo and references to portfolio have more chances to get attention from recruiters. This is just my opinion.

Oh, interesting! I hadn't thought about that. So then, should we move all the contributors who have added a profile image to the top of the list? What if everyone *has* added their image? A fun issue to work on might be to randomize which contributors are listed on page load, to be more democratic. 🤔

**Comment by will-s-205** [comment]
Good point. Let me create an issue

**Pull request merged**
