### PR TITLE
Theme toggle added across the pages PART2

### PR DESCRIPTION
**Pull request by will-s-205**
corresponding issue: https://github.com/michaella23/bootcamp-collab/issues/76

### CODE REVIEW

**Comment by bbrazis** [comment]
Hi @will-s-205, it looks like the contrast on the contributor cards fails accessibility checks when dark mode is toggled. I would suggest adding a line in your code for setting the color of the parent element when dark mode is toggled. The default paragraph color should work.

Also, I wanted to say that the new toggle looks great!

**Comment by will-s-205** [comment]
Hi @bbrazis. Thanks for your feedback. This PR was created as part of the efforts to replace UI of the theme button by toggle. It was never intended to fix accessibility checks when dark mode is toggled. Please create a new issue specifically for accessibility checks. Thanks

**Comment by Kuanchiliao1** [comment]
The new switch looks and works great for me, love it 💜

**Review by michaella23 — APPROVED** [review]
Toggle looks good, theme is changed on all site pages, no issues at smaller viewport size. Thank you.

**Pull request merged**
